### ISSUE TITLE
Ignore `/vendor` IFF we turn on project config

### ISSUE THREAD

**Issue by johndwells** [onedarnleyroad/craftcms#10]
I don't know if this is something we code, can add as part of our (currently non-existent) setup script, or just document in the comments...

**Comment by nathanedwards** [comment]
Are we ever going to turn on project config though....It's such a conscious and, for us, rare decision to do that, that I think we can just make this a more manual process.

Also I don't know how to conditionally do that with the `post-create-project-cmd` without writing a fairly convoluted PHP script to edit `.gitignore.default`
