### ISSUE TITLE
Fix typos preventing successful build

### ISSUE THREAD

**Issue by saltymouse** [onedarnleyroad/craftcms#27]
Brilliant Craft 3 starter—one of the few that actually works as expected!

When spinning it up on my machine, I noticed two simple typos that prevented successful building, however.

- [Extra `y` snuck in tailwind.css](https://github.com/onedarnleyroad/craftcms/blob/master/src/scss/tailwind.css#L2)
- [`@` alias pointing to wrong directory?](https://github.com/onedarnleyroad/craftcms/blob/master/webpack.settings.js#L33)

I have a branch on [my fork with these changes fixed](https://github.com/saltymouse/craftcms/commit/6d9b7e6738c826c598f320fe3f0078c75e256135) if you'd like a pull-request.

**Comment by johndwells** [comment]
@saltymouse Thanks for the contributions! Nice catch, I'd be happy to merge your pull request.

Admittedly, the front-end build stuff we haven't really tested or used much, our focus has mostly been on dialing in the Craft setup. I'm happy to hear you've found it useful!

**Comment by johndwells** [comment]
@saltymouse Finally got around to merging your fix - thanks again for your contribution!

As I said, this is still a relatively under-baked side of this repo. The Craft side is pretty active, but I'm not 100% happy with the front-end build setup. Always happy to have feedback. :)
