### ISSUE TITLE
Error w/Default Mail Setup

### ISSUE THREAD

**Issue by kerns** [onedarnleyroad/craftcms#30]
Are there subsequent steps one should take to have mail working or has something broken? I am not doing more than testing the email config of a default installation.

<img width="837" alt="Screenshot 2022-02-18 at 11 51 14" src="https://user-images.githubusercontent.com/20254/154669377-f0589bbb-847f-4de8-9400-055208abefde.png">

**Comment by johndwells** [comment]
@kerns Keep in mind that "testing" in that context is actually testing the settings you've put into the form fields, _not_ what has been overridden in `config/app` (or previously saved settings from the db/project config).

The only way to really "test" the local configuration would be to replicate what has been overridden in `config/app.php`.

To be clear, the local configuration is set to use Mailhog, which comes with DDEV out of the box: https://ddev.readthedocs.io/en/latest/users/developer-tools/#email-capture-and-review
